services:
  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    hostname: who-server
    restart: unless-stopped
    #ports:
    #  - 5002:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`who.next-etl.com`)
      - traefik.http.routers.whoami.entrypoints=web, websecure
      - traefik.http.routers.whoami.tls=true
      - traefik.http.routers.whoami.tls.certresolver=letsencrypt
      - traefik.http.services.whoami.loadBalancer.server.port=80
    networks:
      - traefik-network
networks:
  traefik-network:
    external: true
