services:
  wg-easy:
    environment:
      - LANG=${LANG}
      - WG_HOST=${WG_HOST}
      - PASSWORD=${PASSWORD}
      - PORT=${PORT}
      - WG_PORT=${WG_PORT}
      - WG_CONFIG_PORT=${WG_CONFIG_PORT}
      - WG_DEFAULT_ADDRESS=${WG_DEFAULT_ADDRESS}
      - WG_DEFAULT_DNS=${WG_DEFAULT_DNS}
      - WG_MTU=${WG_MTU}
      - WG_PERSISTENT_KEEPALIVE=${WG_PERSISTENT_KEEPALIVE}
      - UI_CHART_TYPE=${UI_CHART_TYPE}
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    hostname: wg-server
    volumes:
      - ${HOME}/.docker/wg-easy/configs:/etc/wireguard:ro
    ports:
      - ${WG_PORT}:${WG_PORT}/udp
    # - ${PORT}:${PORT}/tcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.wg.rule=Host(`wg.${WG_HOST}`)
      - traefik.http.routers.wg.entrypoints=websecure
      - traefik.http.routers.wg.tls=true
      - traefik.http.routers.wg.tls.certresolver=letsencrypt
      - traefik.http.services.wg.loadBalancer.server.port=${PORT}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - traefik-network
networks:
  traefik-network:
    external: true
