services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=${TZ}
    #      - UID=1000  #${id -u}
    #      - GID=1000  #${id -g}
    ports:
      - 80:80
      - 443:443
     # - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/.docker/traefik/logs:/var/log/traefik/
      - ${HOME}/.docker/traefik/configs/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${HOME}/.docker/traefik/certs/acme.json:/etc/traefik/certs/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN_NAME}`)
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-secure.service=api@internal
    #      - traefik.http.routers.traefik-secure.tls.domains[0].main=${DOMAIN_NAME}
    #      - traefik.http.routers.traefik-secure.tls.domains[0].sans=dockge.${DOMAIN_NAME}
    networks:
      - traefik-network
networks:
  traefik-network:
    external: true
