version: "3.9"
services:
  sftpgo:
    image: drakkan/sftpgo:latest
    container_name: sftpgo
    volumes:
      - "./config:/config"
      - "./data:/srv/sftpgo"
    ports:
      - "22:22"
      - "18080:18080"
      - "8080:8080"
    restart: unless-stopped
