version: "3.8"
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db
      - "./mongod.yml:/etc/mongod.yml"
      - ./data/log:/var/log/mongodb
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
