services:
  dockge:
    image: louislam/dockge:latest
    restart: unless-stopped
    container_name: dockge
    hostname: dockge-server
   # user: "${UID}:${GID}"
    #ports:
    #  - 5001:5001
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockge.rule=Host(`dockge.next-etl.com`)
      - traefik.http.routers.dockge.entrypoints=web, websecure
      - traefik.http.routers.dockge.tls=true
      - traefik.http.routers.dockge.tls.certresolver=letsencrypt
      - traefik.http.services.dockge.loadBalancer.server.port=5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/dockge/data:/app/data
      - ${HOME}/.docker:/app/stacks
    environment:
      - DOCKGE_STACKS_DIR=/app/stacks
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true

